---
VC_HOSTNAME: vcenter1
VCUSER: user
VCPASS: pass
VH_CLUSTERS:
  - DC0_C0
  - DC0_C1
VHC_NODES:
  - DC0_C0_H0
  - DC0_C0_H1
  - DC0_C0_H2
  - DC0_C1_H0
  - DC0_C1_H1
  - DC0_C1_H2
CLUSTER_NU:
  - 0
  - 1
NODE_NU:
  - 0
  - 1
  - 2
...
