---
- name: apply the default firewalld config
  hosts: all
  become: yes

  tasks:
    - firewalld:
        zone: work
        permanent: true
        source: 192.168.X.X/24
        state: enabled

    - firewalld:
        zone: work
        permanent: true
        source: 192.168.X.X/24
        state: enabled

    - firewalld:
        zone: work
        permanent: true
        source: 192.168.X.X/24
        state: enabled

    - firewalld:
        zone: work
        permanent: true
        source: 192.168.X.X/24
        state: enabled

    - firewalld:
        zone: drop
        permanent: true
        interface: ens192 
        state: enabled

    - service:
        name: firewalld
        state: restarted
        enabled: true
...
