---
- name: patch libvirt guests
  hosts: sandbox
  gather_facts: yes

  tasks:
    - name: Yum patch server
      yum:
        update_cache: yes
        name: "*"
        state: latest
        update_cache: yes
      when:
        ansible_distribution == 'CentOS'
        or
        ansible_distribution == 'RedHat'

    - name: DNF patch server
      dnf:
        name: "*"
        state: latest
      when:
        ansible_distribution == 'Fedora'
        and
        ansible_distribution_version > '21'

    - name: Comparing last kernel and running kernel
      shell: |
        LAST_KERNEL=$(rpm -q --last kernel | perl -pe 's/^kernel-(\S+).*/$1/' | head -1)
        CURRENT_KERNEL=$(uname -r)

        if [[ $LAST_KERNEL != $CURRENT_KERNEL ]]; then
          # Set reboot flag
          touch /tmp/reboot
        fi

    - name: Checking if reboot flag exists
      stat:
        path: /tmp/reboot
        checksum_algorithm: sha256
      register: reboot

    - name: Clearing reboot flag
      file:
        path: /tmp/reboot
        state: absent
      when: reboot.stat.exists == true

    - name: Rebooting host(s).
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      when: reboot.stat.exists == true

