---
- name: poweroff libvirt guests
  hosts: localhost

  tasks:
    - name: get vm info
      virt: command=info
      register: virt_info

    - name: power off vms 
      virt: name={{item}} command=shutdown
      when: virt_info[item]['state'] != 'shutdown'
      with_items:
         - fjb
         - fserver1
