---
- name: poweron libvirt guests
  hosts: localhost

  tasks:
    - name: get list of vms
      shell: virsh list --all |awk 'NR > 2 {print $2}'
      register: kvm_guests

    - name: get vm info
      virt: command=info
      register: virt_info

    - name: power on vms 
      virt: name={{kvm_guests.stdout}} command=shutdown
      when: virt_info[kvm_guests.stdout]['state'] != 'shutdown'
