---
- name: poweron libvirt guests
  hosts: localhost

  tasks:
    - name: start libvirtd
      service: name=libvirtd state=started enabled=yes
      register: libvirtd

    - name: wait for libvirtd to be resident
      pause: seconds=20
      when: libvirtd.changed

    - name: get list of instances
      virt: command=list_vms
      register: virt_instances

    - name: get vm info
      virt: command=info
      register: virt_info

    - name: validate all instances are running 
      virt: name={{item}} command=start
      when: virt_info[item]['state'] != 'running'
      with_items:
           - fjb 
           - fserver1
           - splunk1
           - pulp1
