---
- name: Public key is deployed to managed hosts for Ansible
  hosts: all

  tasks:
  - name: Ensure key is in ansible user's ~/.ssh/authorized_hosts
    authorized_key:
      user: ansible
      state: present
      key: '{{ item }}'
    with_file:
      - ~/.ssh/id_rsa.pub
...

