---
- name: Install and enable cockpit for monitoring and management
  hosts: all

  tasks:

  - name: Ensure cockpit is installed
    package:
      name: cockpit
      state: present

  - name: add cockpit to the host firewall rules
    firewalld:
      zone: work
      service: cockpit
      permanent: yes
      state: enabled

  - name: Enable and Start Cockpit
    systemd:
     name: cockpit.socket
     enabled: true
     state: started
