---
- name: Get the Cluster Info in VCenter
  vmware_cluster_info:
    validate_certs: no
    hostname: "{{ VC_HOSTNAME }}"
    username: "{{ VCUSER }}"
    password: "{{ VCPASS }}"
    cluster_name: "{{ item }}"
  register: vmw_cluster_facts
  loop: "{{ VH_CLUSTERS }}"
  delegate_to: localhost
  tags:
    - cluster-facts

- name: write output to a file
  lineinfile:
    create: yes
    regexp: "NONEEXISTENTLINE"
    path: ./log/cluster_facts.{{vmw_cluster_facts.results[item].item}}.{{ ansible_date_time.date }}.json
    line: "{{ vmw_cluster_facts.results[item].clusters | to_nice_json }}"
  loop: "{{ CLUSTER_NU }}"
  tags:
    - cluster-facts
...
