---
- name: Get the Virtual Machines in VCenter
  vmware_vm_info:
    validate_certs: no
    hostname: "{{ VC_HOSTNAME }}"
    username: "{{ VCUSER }}"
    password: "{{ VCPASS }}"
  register: virtual_machine_facts
  tags:
    - guests
    - instances
    - vm-facts

- name: write output to a file
  lineinfile:
    create: yes
    regexp: "NONEEXISTENTLINE"
    path: ./log/virtual_machine_facts.{{ item.guest_name }}.{{ ansible_date_time.date }}.json
    line: "{{ item | to_nice_json }}"
  loop: "{{ virtual_machine_facts.virtual_machines }}"
  tags:
    - guests
    - instances
    - vm-facts
...

