---
- name: Get info about the vcenter
  vmware_about_info:
    validate_certs: no
    hostname: "{{ VC_HOSTNAME }}"
    username: "{{ VCUSER }}"
    password: "{{ VCPASS }}"
  register: vcenter_about_info
  tags:
    - vcenter-facts

- name: write output to a file
  lineinfile:
    create: yes
    regexp: "NONEEXISTENTLINE"
    path: ./log/vcenter_facts.{{ ansible_date_time.date }}.json
    line: "{{ vcenter_about_info | to_nice_json }}"
  tags:
    - vcenter-facts
...