---
- name: Install k3s to the manager
  hosts: head
  become: yes

  tasks:
  - name: install k3s to the manager
    shell: 'curl -sfL https://get.k3s.io | sh -'
    args:
      creates: /usr/local/bin/k3s


...
