---
- name: Public key is deployed to managed hosts for Ansible
  hosts: all
  become: yes
  vars_files:
    - ./vars/pi-boot.yml


  tasks:
  - name: Configure options in /boot/config.txt.
    lineinfile:
      dest: /boot/config.txt
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      insertafter: EOF
      state: present
    with_items: "{{ raspberry_pi_boot_config_options }}"

  - name: Configure options in /etc/rc.local.
    lineinfile:
      dest: /etc/rc.local
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      insertbefore: "^exit"
      state: present
    with_items: "{{ raspberry_pi_rc_local_options }}"

...

