---
#this playbook copies over the files for stigging firefox linux systems.
- name: apply the firefox stig
  hosts: {{ targets }} 

  tasks:
  - file :
     path: /usr/lib64/firefox/defaults/preferences/
     state: directory

  - copy:
     src: ./autoconfig.js
     dest: /usr/lib64/firefox/defaults/preferences/
     mode: 640

  - copy:
     src: ./mozilla.cfg
     dest: /usr/lib64/firefox/
     mode: 640


