---
#this playbook copies over the files for stigging firefox linux systems.
- name: apply the firefox stig
  hosts: storm havok odin kratos beast rook phoenix wolverine abyss dd-001 dd-002 alpha-las1 loki seeker juggernaut colossus
  remote_user: nimdax

  tasks:
  - file :
     path: /usr/lib64/firefox/defaults/preferences/
     state: directory

  - copy:
     src: /home/nimdax/bin/mozstig/autoconfig.js
     dest: /usr/lib64/firefox/defaults/preferences/
     mode: 640

  - copy:
     src: /home/nimdax/bin/mozstig/mozilla.cfg
     dest: /usr/lib64/firefox/
     mode: 640


