---
#this playbook hits all hosts runs the local inventory report script and fetches it.
- name: run and retrieve the inventory report from all hosts
  hosts: instances

  tasks:
  - name: copy the inventory file over if it is updated
    copy:
      src: files/inventory.sh
      dest: /usr/local/bin/
      mode: 0755
      owner: root
      group: root

  - copy:
     src: files/get-inventory.sh
     dest: /usr/local/bin/
     mode: 0755
     owner: root
     group: root

  - command: "restorecon -R /usr/local/bin"

  - shell: "touch t-inventory-t.log;rm *-inventory-*.log"

  - name: run the inventory script and write the output to a file
    command: "/usr/local/bin/get-inventory.sh"

  - shell: "find . -maxdepth 1 -type f |grep inventory |cut -d '/' -f2 "
    register: files_to_copy

  - fetch:
     src: ~/{{ files_to_copy.stdout }}
     dest: /var/www/html/pub/inventory/
     mode: 0644
     flat: yes

