---
- name: Install podman to the pis
  hosts: all

  tasks:
  - name: add the podman apt repository
    lineinfile:
      path: /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
      line: 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Raspbian_10/ /'
      create: yes

  - name: add the podpam repository key
    apt_key:
      url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Raspbian_10/Release.key
      state: present

  - name: install podman to the pis
    apt: 
      name: podman
      state: latest
      update_cache: yes
...
