---
- name: install rsyslog and setup client for centralized rsyslog and audit log
  hosts: some-ansible-client

  tasks:

  - name: "Ensure rsyslog is installed"
    package:
      name="{{item}}"
      state=present
    with_items:
      - rsyslog

  - name: "Ensure rsyslog-gnutls is installed"
    package:
      name="{{item}}"
      state=present
    with_items:
      - rsyslog-gnutls

  - name: "Ensure gnutls-utils is installed"
    package:
      name="{{item}}"
      state=present
    with_items:
      - gnutls-utils


  - name: "Ensure audit is installed"
    package:
      name="{{item}}"
      state=present
    with_items:
      - audit

  - name: "remove audispd-plugins"
    package:
      name="{{item}}"
      state=absent
    with_items:
      - audispd-plugins

  - name: disable legacy log forwarding
    shell: sed -i 's/^*.* /#*.*/' /etc/rsyslog.conf

  - name: filter audit log messages from local messages log
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: '#filter audit log messages for local messages log'
      line: '#filter audit log messages for local messages log'
      insertafter: '^#### RULES ####'
      state: present

  - name: filter audit log messages from local messages log+
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: ':programname, isequal, "audit" stop'
      line: ':programname, isequal, "audit" stop'
      insertafter: '^#filter audit log messages for local messages log'
      state: present

  - name: filter audit log messages from local messages log++
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: ':programname, isequal, "audispd" stop'
      line: ':programname, isequal, "audispd" stop'
      insertafter: '^:programname, isequal, "audit" stop'
      state: present

  - name: Create the tls.conf file for encrypted rsyslog
    copy:
      src: './tls.conf'
      dest: '/etc/rsyslog.d/tls.conf'
      owner: root
      group: root
      mode: 0644

  - name: add log server to hosts file
    lineinfile:
      path: /etc/hosts
      line: '192.168.X.X syslog1 syslog1.subdomain.domain'

  - name: enable auditd stream to rsyslog
    lineinfile:
      path: /etc/audisp/plugins.d/syslog.conf
      regexp: '^active = no'
      line: 'active = yes'

  - name: Restore file selinux context on certs
    command: 'restorecon -Rv /etc/pki/rsyslog'

  - name: Enable service rsyslog
    service:
      name: "{{item}}"
      enabled: "yes"
      state: "restarted"
    with_items:
      - rsyslog

