---
#this playbook copies over the stig.json file for chrome linux systems.
- name: apply the chrome stig
  hosts: {{ targets }} 

  tasks:
  - file :
     path: /etc/opt/chrome/policies/managed
     state: directory

  - copy:
     src: ./stig.json
     dest: /etc/opt/chrome/policies/managed/
     mode: 644

