---
#this playbook copies over the files for stigging oracle jre1.8 linux systems.
- name: apply the oracle jre 1.8 stig
  hosts: {{ targets }} 

  tasks:
  - file :
     path: /etc/.java/deployment/
     state: directory

  - copy:
     src: ./deployment.properties
     dest: /etc/.java/deployment/
     mode: 640

  - copy:
     src: ./deployment.config
     dest: /etc/.java/deployment/
     mode: 640


