---
apiVersion: v1

kind: Pod

metadata:
  name: testpod

spec:
  containers:
    - name: db1
      image: postgres:12
      ports:
        - containerPort: 5432
          hostPort: 5432
          protocol: TCP
      env:
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: guest

