---
- name: Setup the provisioning server for the environment
  hosts: prov1
  become: yes

  tasks:

  - name: "Ensure the packages are installed"
    package:
      name="{{item}}"
      state=present
    with_items:
      - dhcp
      - tftp
      - tftp-server
      - syslinux
      - httpd
      - mod_ssl
      - xinetd
      - syslinux-tftpboot

  - name: add services to the host firewall rules
    firewalld:
      service: "{{item}}"
      permanent: yes
      state: enabled
      zone: work
    with_items:
      - http
      - https
      - tftp
      - dhcp

  - name: add ports to the host firewall rules
    firewalld:
      port: "{{item}}"
      permanent: yes
      state: enabled
      zone: work
    with_items:
      - 69/tcp
      - 69/udp
      - 4011/udp

  - name: update the httpd ssl configuration
    lineinfile:
      path: /etc/httpd/conf.d/ssl.conf
      regexp: '^SSLProtocolProtocol all -SSLv3'
      line: 'SSLProtocol -all +TLSv1.2'

  - file :
     path: /var/www/html/ks/
     state: directory
     mode: 0755
     owner: root
     group: root

  - copy:
     src: ./pxe-images/fserver.cfg
     dest: /var/www/html/ks/
     mode: 0644

  - name: restore selinux file contexts
    command: "restorecon -R /var/www/"

  - name: Enable service httpd
    service:
      name: "{{item}}"
      enabled: "yes"
      state: "restarted"
    with_items:
      - httpd

  - file :
     path: /var/lib/tftpboot/networkboot/fedora/
     state: directory
     mode: 0755
     owner: root
     group: root

  - shell: "curl -4 https://ewr.edge.kernel.org/fedora-buffet/fedora/linux/releases/32/Everything/x86_64/os/images/pxeboot/{vmlinuz,initrd.img} -o /var/lib/tftpboot/networkboot/fedora/{vmlinuz,initrd.img}"

  - copy:
     src: "{{item}}"
     dest: /var/lib/tftpboot/
     mode: 0640
    with_items:
     - ./pxe-images/pxelinux.0
     - ./pxe-images/menu.c32
     - ./pxe-images/memdisk
     - ./pxe-images/mboot.c32
     - ./pxe-images/chain.c32
     - ./pxe-images/ldlinux.c32
     - ./pxe-images/libutil.c32

  - file :
     path: /var/lib/tftpboot/pxelinux.cfg/
     state: directory
     mode: 0755
     owner: root
     group: root

  - copy:
     src: ./pxe-images/default
     dest: /var/lib/tftpboot/pxelinux.cfg/
     mode: 0644

  - copy:
     src: ./pxe-images/tftp
     dest: /etc/xinet.d/
     mode: 0644

  - name: restore selinux file contexts
    command: "restorecon -R /var/lib/"

  - name: Enable tftp service
    service:
      name: "{{item}}"
      enabled: "yes"
      state: "restarted"
    with_items:
      - tftp
      - xinetd

  - copy:
     src: ./pxe-images/dhcpd.conf
     dest: /etc/dhcp/
     mode: 0640

  - name: restore selinux file contexts
    command: "restorecon -R /etc/"

  - name: Enable dhcp service
    service:
      name: "{{item}}"
      enabled: "yes"
      state: "restarted"
    with_items:
      - dhcpd


