---
- name: push configuration files and scripts to comply with the DISA STIG for RHEL 7
  hosts: "{{R7HOSTS}}"

  tasks:
  - name: "Ensure packages are installed"
    package:
     name: "{{item}}"
     state: present
    with_items:
     - vlock
     - audit
     - audispd-plugins
    tags:
     - etc
     - packages  

  - name: copy over the script to check for unowned or ungrouped files
    copy:
      src: ./utils/file-owner-check.sh
      dest: /etc/cron.daily/
      mode: 0750
      owner: root
      group: root
    tags:
      - etc
      - stig-file-owner

  - name: copy over the DISA login banner for Command Line
    copy:
      src: "{{item}}"
      dest: /etc/
      mode: 0644
      owner: root
      group: root
    with_items:
      - ./banner/issue
      - ./banner/issue.net
    tags:
      - stig-banner
      - etc

  - name: copy over the DISA shell session parameters for Command Line
    copy:
      src: "{{item}}"
      dest: /etc/profile.d/
      mode: 0755
      owner: root
      group: root
    with_items:
      - ./profiled/stig-timeout.sh
      - ./profiled/stig-timeout.csh
      - ./profiled/stig-umask.sh
      - ./profiled/stig-timeout.csh
      - ./profiled/vlock-alias.sh
      - ./profiled/vlock-alias.csh
    tags:
      - stig-timeout
      - etc

  - name: Configure SSH daemon
    copy:
      src: ./ssh/sshd_config
      dest: /etc/ssh/
      mode: 0600
      owner: root
      group: root
    tags:
        - etc
        - ssh-config  

  - name: Configure Audit daemon
    copy:
      src: ./audit/auditd.conf
      dest: /etc/audit/
      mode: 0600
      owner: root
      group: root
    tags:
      - etc
      - stig-audit

  - name: Confiure Audit Rules
    copy:
      src: ./audit/audit.rules
      dest: "{{item}}"
      mode: 0600
      owner: root
      group: root
    with_items:
      - /etc/audit/rules.d/
      - /etc/audit/
    tags:
      - etc
      - stig-audit

  - name: Reset SE Linux File Context on the etc directory structructure
    command: "restorecon -R /etc"
    tags:
      - utils
      - etc

  - name: Restart Services
    service:
      name: "{{item}}"
      enabled: "yes"
      state: "restarted"
    with_items:
      - sshd
    tags:
      - etc
      - ssh-config
...

