---
- name: push configuration files and scripts to comply with the DISA STIG
  hosts: fcon-n2

  tasks:
  - name: copy over the script to remove old logs and empty files from var
    copy:
      src: ./utils/purge-old-files.sh
      dest: /etc/cron.daily/
      mode: 0750
      owner: root
      group: root
    tags:
      - utils
      - etc

  - name: copy over the script to check for unowned or ungrouped files
    copy:
      src: ./utils/file-owner-check.sh
      dest: /etc/cron.daily/
      mode: 0750
      owner: root
      group: root
    tags:
      - etc
      - stig-file-owner

  - name: copy over the DISA login banner for Command Line
    copy:
      src: "{{item}}"
      dest: /etc/
      mode: 0644
      owner: root
      group: root
    with_items:
      - ./banner/issue
      - ./banner/issue.net
    tags:
      - stig-banner
      - etc

  - name: copy over the DISA shell session timeout for Command Line
    copy:
      src: "{{item}}"
      dest: /etc/profile.d/
      mode: 0755
      owner: root
      group: root
    with_items:
      - ./profiled/stig-timeout.sh
      - ./profiled/stig-timeout.csh
    tags:
      - stig-timeout
      - etc

  - command: "restorecon -R /etc"
    tags:
      - utils
      - etc
...
