---
- name: push configuration files and scripts to comply with the DISA STIG for RHEL 7
  hosts: "{{R7HOSTS}}"

  tasks:
  - name: "Ensure packages are installed"
    package:
     name: "{{item}}"
     state: present
    with_items:
     - vlock
     - audit
     - audispd-plugins
     - selinux-policy
     - selinux-policy-targeted
     - screen
     - dracut-fips
     - fipscheck
     - aide
     - rsyslog
     - pam_pkcs11
     - pcsc-lite
     - opensc
     - yum-utils
    tags:
     - etc
     - packages
     - High  

  - name: "Remove prohibited packages"
    package:
      name: "{{item}}"
      state: absent
    with_items:
      - ypserv
      - rsh-server
      - telnet-server
    tags:
      - stig-packages
      - High


  - name: copy over the script to check for unowned or ungrouped files
    copy:
      src: ./utils/file-owner-check.sh
      dest: /etc/cron.daily/
      mode: 0750
      owner: root
      group: root
    tags:
      - etc
      - stig-file-owner


  - name: copy over the DISA login banner for Command Line
    copy:
      src: "{{item}}"
      dest: /etc/
      mode: 0644
      owner: root
      group: root
    with_items:
      - ./banner/issue
      - ./banner/issue.net
    tags:
      - stig-banner
      - etc

  - name: copy over the DISA shell session parameters for Command Line
    copy:
      src: "{{item}}"
      dest: /etc/profile.d/
      mode: 0755
      owner: root
      group: root
    with_items:
      - ./profiled/stig-timeout.sh
      - ./profiled/stig-timeout.csh
      - ./profiled/stig-umask.sh
      - ./profiled/stig-timeout.csh
      - ./profiled/vlock-alias.sh
      - ./profiled/vlock-alias.csh
    tags:
      - stig-timeout
      - etc

  - name: Configure SSH daemon
    copy:
      src: ./ssh/sshd_config
      dest: /etc/ssh/
      mode: 0600
      owner: root
      group: root
    tags:
      - etc
      - stig-ssh
      - High  

  - name: Configure Audit daemon
    copy:
      src: ./audit/auditd.conf
      dest: /etc/audit/
      mode: 0600
      owner: root
      group: root
    tags:
      - etc
      - stig-audit
      - High

  - name: Confiure Audit Rules
    copy:
      src: ./audit/audit.rules
      dest: "{{item}}"
      mode: 0600
      owner: root
      group: root
    with_items:
      - /etc/audit/rules.d/
      - /etc/audit/
    tags:
      - etc
      - stig-audit
      - High

  - name: filter audit log messages from local messages log
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: '#filter audit log messages for local messages log'
      line: '#filter audit log messages for local messages log'
      insertafter: '^#### RULES ####'
      state: present
    tags:
      - etc
      - rsyslog-config

  - name: filter audit log messages from local messages log+
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: ':programname, isequal, "audit" stop'
      line: ':programname, isequal, "audit" stop'
      insertafter: '^#filter audit log messages for local messages log'
      state: present
    tags:
      - etc
      - rsyslog-config

  - name: filter audit log messages from local messages log++
    lineinfile:
      path: /etc/rsyslog.conf
      regexp: ':programname, isequal, "audispd" stop'
      line: ':programname, isequal, "audispd" stop'
      insertafter: '^:programname, isequal, "audit" stop'
      state: present
    tags:
      - etc
      - rsyslog-conf

  - name: Configure Sysctl Securit Limits
    copy:
      src: ./modprob/limits.conf
      dest: /etc/security/
      mode: 0640
      owner: root
      group: root
    tags:
      - etc
      - stig-sysctl
      - Hign  

  - name: Configure Sysctl Configuration
    copy:
      src: ./modprob/sysctl.conf
      dest: /etc/security/
      mode: 0640
      owner: root
      group: root
    tags:
      - etc
      - stig-sysctl
      - High

  - name: Reload Sysctl
    command: "sysctl -p /etc/sysctl.conf"
    tags:
      - etc
      - stig-sysctl
  
  - name: Disable Restricted Protocols and Filesystem Modules
    copy:
      src: ./modprob/stig.conf
      dest: /etc/modprobe.d/
      owner: root
      group: root
      mode: 0640
    tags:
      - etc
      - stig-modprobe

  - name: Disable bluetooth altogether
    systemd:
      name: bluetooth.service
      state: stopped
      enabled: no
      masked: yes
    ignore_errors: yes
    tags:
      - stig-modprobe
      - stig-bluetooth

  - name: Ensure SELinux is enforcing targeted
    selinux:
      policy: targeted
      state: enforcing
    tags:
      - etc
      - stig-selinux
      - High

  - name: Make the SELinux configuration immutable
    command: "chattr +i /etc/selinux/config"
    tags:
      - etc
      - stig-selinux

  - name: Remove unneeded users
    user:
      name: "{{item}}"
      state: absent
      remove: yes
    with_items:
      - uucp
      - sync
      - news
      - games
      - gopher
      - shutdown
    ignore_errors: yes
    tags:
      - etc
      - stig-users

  - name: check prelink binary installed
    stat:
      path: /usr/sbin/prelink
    register: prelink_exists
    tags:
      - grub2_enable_fips_mode
      - high

  - name: disable prelink
    lineinfile:
      dest: /etc/sysconfig/prelink
      regexp: ^#?PRELINKING
      line: PRELINKING=no
    tags:
      - grub2_enable_fips_mode
      - high
      - etc

  - name: revert prelinking binaries
    command: /usr/sbin/prelink -ua
    when:
      - prelink_exists.stat.exists
    tags:
      - grub2_enable_fips_mode
      - high

  - name: Check if system supports AES-NI
    command: grep -q -m1 -o aes /proc/cpuinfo
    failed_when: aesni_supported.rc > 1
    register: aesni_supported
    check_mode: false
    tags:
      - grub2_enable_fips_mode
      - high

  - name: Ensure dracut-fips-aesni is installed
    package:
      name: dracut-fips-aesni
      state: present
    when:
      - aesni_supported.rc == 0
    tags:
      - grub2_enable_fips_mode
      - high
        
  - name: Reset SE Linux File Context on the etc directory structructure
    command: "restorecon -R /etc"
    tags:
      - utils
      - etc

  - name: Restart Services
    service:
      name: "{{item}}"
      enabled: "yes"
      state: "restarted"
    with_items:
      - sshd
      - rsyslog
    tags:
      - etc
      - stig-ssh
      - stig-rsyslog

...

