---
- name: install rsyslog and setup server for centralized rsyslog and audit log
  hosts: rsyslog1
  become: yes

  tasks:

  - name: "Ensure rsyslog is installed"
    package:
      name="{{item}}"
      state=present
    with_items:
      - rsyslog
      - rsyslog-gnutls
      - gnutls-utils
      - bind-utils

  - name: "Ensure audit is installed"
    package:
      name="{{item}}"
      state=present
    with_items:
      - audit

  - name: "remove audispd-plugins"
    package:
      name="{{item}}"
      state=absent
    with_items:
      - audispd-plugins

  - copy:
     src: ca.tmpl
     dest: /etc/pki/rsyslog/
     mode: 0640
     owner: root
     group: root

  - name: generate a private CA
    command: "certtool --generate-privkey --outfile /etc/pki/rsyslog/ca-key.pem --sec-param High"

  - copy:
     src: serv.tmpl
     dest: /etc/pki/rsyslog/
     mode: 0640
     owner: root
     group: root

  - copy:
     src: create-serv-cert.sh
     dest: /etc/pki/rsyslog/
     mode: 0700
     owner: root
     group: root

  - copy:
     src: remotelogs
     dest: /etc/logrotate.d/
     mode: 0640
     owner: root
     group: root


  - name: generate a private CA
    command: "certtool --generate-self-signed --load-privkey /etc/pki/rsyslog/ca-key.pem --template /etc/pki/rsyslog/ca.tmpl --outfile /etc/pki/rsyslog/ca-cert.pem"

  - name: generate server cert
    command: "/etc/pki/rsyslog/create-serv-cert.sh"

  - name: restore selinux file contexts
    command: "restorecon -R /etc/"

  - name: Copy over the rsyslog.conf file
    copy:
      src: './rsyslog.conf'
      dest: '/etc/rsyslog.conf'
      owner: root
      group: root
      mode: 0644

  - name: enable auditd stream to rsyslog
    lineinfile:
      path: /etc/audisp/plugins.d/syslog.conf
      regexp: '^active = no'
      line: 'active = yes'

  - name: Enable service rsyslog
    service:
      name="{{item}}"
      enabled="yes"
      state="restarted"
    with_items:
      - rsyslog

  - name: Cleanup
    file:
      path: /etc/pki/rsyslog/{{item}}
      state: absent
    with_items:
      - ca.tmpl
      - serv.tmpl
      - create-serv-cert.sh

  - name: add syslog to the host firewall rules
    firewalld:
      service: syslog
      permanent: yes
      state: enabled
